'use client'

import { ThemeProvider } from 'next-themes'
import { Geist, Geist_Mono as GeistMono } from 'next/font/google'

import { useDailyReset } from '@/features/task/reset/model/useDailyReset'
import { useKeyboard } from '@/shared/hooks/useKeyboard'
import { cn } from '@/shared/lib/utils'
import { BottomNavigation } from '@/shared/ui/bottom-navigation'
import { Toaster } from '@/shared/ui/sonner'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = GeistMono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { visible } = useKeyboard()
  useDailyReset()
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover, interactive-widget=overlays-content"
        /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div>
            {/* <div className="flex flex-col h-dvh"> */}
            {children}
            {/* // TODO: 뭐가 더 나은지 고민 */}
            <BottomNavigation
              className={cn(
                'transition-[transform] duration-300 ease-in-out',
                visible ? 'translate-y-full' : 'translate-y-0',
              )}
            />
            {/* <BottomNavigation className={cn(visible && 'hidden')} /> */}
            <Toaster />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
